### ISSUE TITLE
Add additional TFM so that framework can provide STJ

### ISSUE THREAD

**Issue by thompson-tomo** [wivuu/Wivuu.JsonPolymorphism#16]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Text.Json as it can be provided by the framework when targeting net 6. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by onionhammer** [comment]
Hi @thompson-tomo 

Would you be interested in submitting a pull-request?

**Comment by thompson-tomo** [comment]
Sure thing

**Comment by onionhammer** [comment]
@thompson-tomo I did find a regression in this version, so I'll investigate it next week; un-publishing for now

**Comment by onionhammer** [comment]
@thompson-tomo 1.0.20 is out now; I've dropped support for .NET standard, since it's no longer used in any versions of .NET which are not out of support.
