### ISSUE TITLE
Incompatible with AutoMapper

### ISSUE THREAD

**Issue by zyofeng** [wivuu/Wivuu.JsonPolymorphism#9]
AutoMapper does not like the fact base class/record is abstract, the problem manifests itself when you try to project with the following exception:

"message": "Cannot dynamically create an instance of type 'xxxx'. Reason: Cannot create an abstract class.",

There are some workaround like creating multiple base classes etc and inherit one another but it would be nice if there is a proper solution.

Any suggestions? Maybe the base class can be made non-abstract ?

**Comment by onionhammer** [comment]
Hi @zyofeng 

You will have to use AutoMapper's `ConstructUsing` function to switch based on the discriminator; i.e.

```C#
_cfg.CreateMap<Animal, AnimalViewModel>()
    .ConstructUsing((s, ctx) =>
        s.Kind switch
        {
            AnmalKind.Insect => ctx.Mapper.Map<InsectViewModel>(s as Insect),
            AnmalKind.Mammal => ctx.Mapper.Map<MammalViewModel>(s as Mammal),
        });

_cfg.CreateMap<Insect, InsectViewModel>().IncludeBase<Animal, AnimalViewModel>.ReverseMap();
_cfg.CreateMap<Mammal, MammalViewModel>().IncludeBase<Animal, AnimalViewModel>.ReverseMap();
```
